import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/components/providers/authContext";
import { Toaster } from "@/components/ui/sonner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ordering System",
  description: "Generated by create next app",
};
const inlineToastStyle = {
  backgroundColor: '#1e40af',
  color: 'white',
  padding: '12px 20px',
  borderRadius: '12px',
  fontWeight: '600',
  fontSize: '16px',
  boxShadow: '0 4px 15px rgba(0,0,0,0.25)',
  display: 'flex',
  alignItems: 'center',
  gap: '0.75rem',
  border: '2px solid #3b82f6',
  transition: 'all 0.3s ease',
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
     <Toaster
  position="top-center"
/>


      
                {children}
        
  
      </body>
    </html>
  );
}
